<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="2" total="10" passed="5" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-28T16:25:02 IST" name="Suite" finished-at="2025-07-28T16:26:04 IST" duration-ms="61495">
    <groups>
      <group name="perchase">
        <method signature="submitOrderTest.SubmitOrder(java.util.HashMap)[pri:0, instance:Selenium.test.submitOrderTest@7fc4780b]" name="SubmitOrder" class="Selenium.test.submitOrderTest"/>
      </group> <!-- perchase -->
      <group name="errorValidation">
        <method signature="errorValidationTest.LoginErrorValidation()[pri:0, instance:Selenium.test.errorValidationTest@13df2a8c]" name="LoginErrorValidation" class="Selenium.test.errorValidationTest"/>
        <method signature="errorValidationTest.ProductErrorValidation()[pri:0, instance:Selenium.test.errorValidationTest@13df2a8c]" name="ProductErrorValidation" class="Selenium.test.errorValidationTest"/>
      </group> <!-- errorValidation -->
      <group name="smoke">
        <method signature="submitOrderTest.SubmitOrder(java.util.HashMap)[pri:0, instance:Selenium.test.submitOrderTest@7fc4780b]" name="SubmitOrder" class="Selenium.test.submitOrderTest"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2025-07-28T16:25:02 IST" name="errorValidationTest" finished-at="2025-07-28T16:25:32 IST" duration-ms="29772">
      <class name="Selenium.test.errorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Selenium.test.errorValidationTest@13df2a8c]" started-at="2025-07-28T16:25:02 IST" name="launchApplication" finished-at="2025-07-28T16:25:13 IST" duration-ms="10715" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:Selenium.test.errorValidationTest@13df2a8c]" started-at="2025-07-28T16:25:13 IST" name="LoginErrorValidation" finished-at="2025-07-28T16:25:14 IST" duration-ms="1096" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or password.tttttt]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or password.tttttt]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Selenium.test.errorValidationTest.LoginErrorValidation(errorValidationTest.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Selenium.test.errorValidationTest@13df2a8c]" started-at="2025-07-28T16:25:14 IST" name="tearDown" finished-at="2025-07-28T16:25:15 IST" duration-ms="331" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Selenium.test.errorValidationTest@13df2a8c]" started-at="2025-07-28T16:25:15 IST" name="launchApplication" finished-at="2025-07-28T16:25:18 IST" duration-ms="3332" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:Selenium.test.errorValidationTest@13df2a8c]" started-at="2025-07-28T16:25:18 IST" name="LoginErrorValidation" finished-at="2025-07-28T16:25:19 IST" duration-ms="638" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or password.tttttt]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or password.tttttt]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Selenium.test.errorValidationTest.LoginErrorValidation(errorValidationTest.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Selenium.test.errorValidationTest@13df2a8c]" started-at="2025-07-28T16:25:19 IST" name="tearDown" finished-at="2025-07-28T16:25:19 IST" duration-ms="370" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Selenium.test.errorValidationTest@13df2a8c]" started-at="2025-07-28T16:25:19 IST" name="launchApplication" finished-at="2025-07-28T16:25:21 IST" duration-ms="2054" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:Selenium.test.errorValidationTest@13df2a8c]" started-at="2025-07-28T16:25:21 IST" name="LoginErrorValidation" finished-at="2025-07-28T16:25:22 IST" duration-ms="625" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or password.tttttt]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or password.tttttt]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Selenium.test.errorValidationTest.LoginErrorValidation(errorValidationTest.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Selenium.test.errorValidationTest@13df2a8c]" started-at="2025-07-28T16:25:22 IST" name="tearDown" finished-at="2025-07-28T16:25:22 IST" duration-ms="315" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Selenium.test.errorValidationTest@13df2a8c]" started-at="2025-07-28T16:25:22 IST" name="launchApplication" finished-at="2025-07-28T16:25:26 IST" duration-ms="3428" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:Selenium.test.errorValidationTest@13df2a8c]" started-at="2025-07-28T16:25:26 IST" name="ProductErrorValidation" finished-at="2025-07-28T16:25:32 IST" duration-ms="5861" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Selenium.test.errorValidationTest@13df2a8c]" started-at="2025-07-28T16:25:32 IST" name="tearDown" finished-at="2025-07-28T16:25:32 IST" duration-ms="305" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Selenium.test.errorValidationTest -->
    </test> <!-- errorValidationTest -->
    <test started-at="2025-07-28T16:25:33 IST" name="submitOrderTest" finished-at="2025-07-28T16:26:04 IST" duration-ms="31158">
      <class name="Selenium.test.submitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Selenium.test.submitOrderTest@7fc4780b]" started-at="2025-07-28T16:25:33 IST" name="launchApplication" finished-at="2025-07-28T16:25:37 IST" duration-ms="4319" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:Selenium.test.submitOrderTest@7fc4780b]" started-at="2025-07-28T16:25:37 IST" name="SubmitOrder" data-provider="getData" finished-at="2025-07-28T16:25:43 IST" duration-ms="5580" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{name=roushan@gmail.com, password=Roushan@123, item=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Selenium.test.submitOrderTest@7fc4780b]" started-at="2025-07-28T16:25:43 IST" name="tearDown" finished-at="2025-07-28T16:25:43 IST" duration-ms="309" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Selenium.test.submitOrderTest@7fc4780b]" started-at="2025-07-28T16:25:43 IST" name="launchApplication" finished-at="2025-07-28T16:25:46 IST" duration-ms="2984" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:Selenium.test.submitOrderTest@7fc4780b]" started-at="2025-07-28T16:25:46 IST" name="SubmitOrder" data-provider="getData" finished-at="2025-07-28T16:25:52 IST" duration-ms="5540" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{name=roushankumar22145@gmail.com, password=Roushan@123, item=IPHONE 13 PRO}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Selenium.test.submitOrderTest@7fc4780b]" started-at="2025-07-28T16:25:52 IST" name="tearDown" finished-at="2025-07-28T16:25:52 IST" duration-ms="366" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Selenium.test.submitOrderTest@7fc4780b]" started-at="2025-07-28T16:25:52 IST" name="launchApplication" finished-at="2025-07-28T16:25:54 IST" duration-ms="1828" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="varifyOrderDisplay(java.util.HashMap)[pri:0, instance:Selenium.test.submitOrderTest@7fc4780b]" started-at="2025-07-28T16:25:54 IST" name="varifyOrderDisplay" data-provider="getData" finished-at="2025-07-28T16:25:57 IST" depends-on-methods="Selenium.test.submitOrderTest.SubmitOrder" duration-ms="2877" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{name=roushan@gmail.com, password=Roushan@123, item=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- varifyOrderDisplay -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Selenium.test.submitOrderTest@7fc4780b]" started-at="2025-07-28T16:25:57 IST" name="tearDown" finished-at="2025-07-28T16:25:58 IST" duration-ms="333" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Selenium.test.submitOrderTest@7fc4780b]" started-at="2025-07-28T16:25:58 IST" name="launchApplication" finished-at="2025-07-28T16:26:01 IST" duration-ms="2902" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="varifyOrderDisplay(java.util.HashMap)[pri:0, instance:Selenium.test.submitOrderTest@7fc4780b]" started-at="2025-07-28T16:26:01 IST" name="varifyOrderDisplay" data-provider="getData" finished-at="2025-07-28T16:26:03 IST" depends-on-methods="Selenium.test.submitOrderTest.SubmitOrder" duration-ms="2739" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{name=roushankumar22145@gmail.com, password=Roushan@123, item=IPHONE 13 PRO}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- varifyOrderDisplay -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Selenium.test.submitOrderTest@7fc4780b]" started-at="2025-07-28T16:26:04 IST" name="tearDown" finished-at="2025-07-28T16:26:04 IST" duration-ms="330" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Selenium.test.submitOrderTest -->
    </test> <!-- submitOrderTest -->
  </suite> <!-- Suite -->
</testng-results>
